import { dummyProductUnit, ProductUnit } from "./ProductUnit";

export interface Product {
    id: string;
    name: string;
    description?: string;
    imageUrl?: string;
    category?: string;
    units?: ProductUnit[];

    createdAt?: Date;
    updatedAt?: Date;
    createdBy?: string;
    updatedBy?: string;
}


export const dummyData : Product[] =  [
  {
    id: "802bec62-0de3-4f87-b7d2-707c74f78f5e",
    name: "Kapal Api Special Mix",
    description: "Kopi instan Kapal Api sachet 10 pcs.",
    imageUrl: "https://via.placeholder.com/150",
    category: "Minuman",
    units: dummyProductUnit,
    createdAt: new Date("2024-01-01"),
    createdBy: "admin",
  },
  {
    id: "702bec62-0de3-4f87-b7d2-707c74f78f5e",
    name: "Energen Cokelat",
    description: "Minuman sereal bergizi rasa cokelat isi 10 sachet.",
    imageUrl: "https://via.placeholder.com/150",
    category: "Minuman",
    units: [
      {
        Id: "f93aef58-7754-4bc1-808a-ffa6fbbda987",
        product_id: "702bec62-0de3-4f87-b7d2-707c74f78f5e",
        unitName: "Sachet",
        price: 5000,
        quantity: 0,
      },
      {
        Id: "c0c3da59-cca8-4142-81a5-579ecf9611c3",
        product_id: "702bec62-0de3-4f87-b7d2-707c74f78f5e",
        unitName: "Box",
        price: 45000,
        quantity: 0,
      }
    ],
    createdAt: new Date("2024-01-02"),
    createdBy: "admin",
  },
  {
    id: "3",
    name: "Indomie Goreng",
    description: "Mi instan goreng isi 5 pcs.",
    imageUrl: "https://via.placeholder.com/150",
    category: "Makanan",
    units: [],
    createdAt: new Date("2024-01-03"),
    createdBy: "admin",
  },
  {
    id: "4",
    name: "Lifebuoy Sabun Batang",
    description: "Sabun batang antiseptik Lifebuoy 85g.",
    imageUrl: "https://via.placeholder.com/150",
    category: "Kebersihan",
    units: [],
    createdAt: new Date("2024-01-04"),
    createdBy: "admin",
  },
  {
    id: "5",
    name: "Rinso Deterjen Cair",
    description: "Deterjen cair 1.6L pouch.",
    imageUrl: "https://via.placeholder.com/150",
    category: "Kebersihan",
    units: [],
    createdAt: new Date("2024-01-05"),
    createdBy: "admin",
  },
  {
    id: "6",
    name: "Sampoerna Mild",
    description: "Rokok filter isi 16 batang.",
    imageUrl: "https://via.placeholder.com/150",
    category: "Rokok",
    units: [],
    createdAt: new Date("2024-01-06"),
    createdBy: "admin",
  },
  {
    id: "7",
    name: "Pocari Sweat",
    description: "Minuman ion botol 500ml.",
    imageUrl: "https://via.placeholder.com/150",
    category: "Minuman",
    units: [],
    createdAt: new Date("2024-01-07"),
    createdBy: "admin",
  },
  {
    id: "8",
    name: "Tissue Paseo",
    description: "Tissue wajah 250 sheets.",
    imageUrl: "https://via.placeholder.com/150",
    category: "Kebutuhan Rumah",
    units: [],
    createdAt: new Date("2024-01-08"),
    createdBy: "admin",
  },
  {
    id: "9",
    name: "Aqua Botol 600ml",
    description: "Air mineral dalam kemasan botol.",
    imageUrl: "https://via.placeholder.com/150",
    category: "Minuman",
    units: [],
    createdAt: new Date("2024-01-09"),
    createdBy: "admin",
  },
  {
    id: "10",
    name: "Roma Biskuit Kelapa",
    description: "Biskuit dengan taburan kelapa.",
    imageUrl: "https://via.placeholder.com/150",
    category: "Makanan",
    units: [],
    createdAt: new Date("2024-01-10"),
    createdBy: "admin",
  },
  // Lanjutkan untuk 20 produk berikutnya dengan pola serupa:
  {
    id: "11",
    name: "Sunlight Jeruk Nipis 755ml",
    description: "Sabun cuci piring cair jeruk nipis.",
    imageUrl: "https://via.placeholder.com/150",
    category: "Kebersihan",
    units: [],
    createdAt: new Date("2024-01-11"),
    createdBy: "admin",
  },
  {
    id: "12",
    name: "Baygon Spray",
    description: "Anti nyamuk aerosol 600ml.",
    imageUrl: "https://via.placeholder.com/150",
    category: "Kebersihan",
    units: [],
    createdAt: new Date("2024-01-12"),
    createdBy: "admin",
  },
  {
    id: "13",
    name: "Bimoli Minyak Goreng 1L",
    description: "Minyak goreng premium 1 liter.",
    imageUrl: "https://via.placeholder.com/150",
    category: "Makanan",
    units: [],
    createdAt: new Date("2024-01-13"),
    createdBy: "admin",
  },
  {
    id: "14",
    name: "Teh Botol Sosro 450ml",
    description: "Teh manis dalam botol.",
    imageUrl: "https://via.placeholder.com/150",
    category: "Minuman",
    units: [],
    createdAt: new Date("2024-01-14"),
    createdBy: "admin",
  },
  {
    id: "15",
    name: "Pepsodent Pasta Gigi 190gr",
    description: "Pasta gigi untuk perlindungan menyeluruh.",
    imageUrl: "https://via.placeholder.com/150",
    category: "Kesehatan",
    units: [],
    createdAt: new Date("2024-01-15"),
    createdBy: "admin",
  },
  {
    id: "16",
    name: "Silver Queen Chunky Bar 65gr",
    description: "Cokelat batangan dengan kacang mete.",
    imageUrl: "https://via.placeholder.com/150",
    category: "Makanan",
    units: [],
    createdAt: new Date("2024-01-16"),
    createdBy: "admin",
  },
  {
    id: "17",
    name: "Tango Wafer Cokelat 130gr",
    description: "Wafer lapis krim cokelat.",
    imageUrl: "https://via.placeholder.com/150",
    category: "Makanan",
    units: [],
    createdAt: new Date("2024-01-17"),
    createdBy: "admin",
  },
  {
    id: "18",
    name: "Mie Sedap Soto",
    description: "Mi instan rasa soto lamongan.",
    imageUrl: "https://via.placeholder.com/150",
    category: "Makanan",
    units: [],
    createdAt: new Date("2024-01-18"),
    createdBy: "admin",
  },
  {
    id: "19",
    name: "Tolak Angin Cair",
    description: "Obat herbal masuk angin dalam sachet cair.",
    imageUrl: "https://via.placeholder.com/150",
    category: "Kesehatan",
    units: [],
    createdAt: new Date("2024-01-19"),
    createdBy: "admin",
  },
  {
    id: "20",
    name: "Good Day Cappuccino",
    description: "Minuman kopi instan rasa cappuccino.",
    imageUrl: "https://via.placeholder.com/150",
    category: "Minuman",
    units: [],
    createdAt: new Date("2024-01-20"),
    createdBy: "admin",
  },
  {
    id: "21",
    name: "Le Minerale 600ml",
    description: "Air mineral dalam botol PET.",
    imageUrl: "https://via.placeholder.com/150",
    category: "Minuman",
    units: [],
    createdAt: new Date("2024-01-21"),
    createdBy: "admin",
  },
  {
    id: "22",
    name: "Molto Pewangi Pakaian 900ml",
    description: "Pelembut dan pewangi pakaian konsentrat.",
    imageUrl: "https://via.placeholder.com/150",
    category: "Kebersihan",
    units: [],
    createdAt: new Date("2024-01-22"),
    createdBy: "admin",
  },
  {
    id: "23",
    name: "Baygon Elektrik Refill",
    description: "Isi ulang anti nyamuk elektrik.",
    imageUrl: "https://via.placeholder.com/150",
    category: "Kebersihan",
    units: [],
    createdAt: new Date("2024-01-23"),
    createdBy: "admin",
  },
  {
    id: "24",
    name: "Gulaku Gula Pasir 1kg",
    description: "Gula pasir putih kemasan 1kg.",
    imageUrl: "https://via.placeholder.com/150",
    category: "Bahan Pokok",
    units: [],
    createdAt: new Date("2024-01-24"),
    createdBy: "admin",
  },
  {
    id: "25",
    name: "Sasa Tepung Bumbu Serbaguna",
    description: "Tepung bumbu siap pakai 210gr.",
    imageUrl: "https://via.placeholder.com/150",
    category: "Bahan Masakan",
    units: [],
    createdAt: new Date("2024-01-25"),
    createdBy: "admin",
  },
  {
    id: "26",
    name: "So Klin Pewangi Refill",
    description: "Pewangi pakaian isi ulang 800ml.",
    imageUrl: "https://via.placeholder.com/150",
    category: "Kebersihan",
    units: [],
    createdAt: new Date("2024-01-26"),
    createdBy: "admin",
  },
  {
    id: "27",
    name: "Luwak White Coffee",
    description: "Kopi instan putih kemasan 10 sachet.",
    imageUrl: "https://via.placeholder.com/150",
    category: "Minuman",
    units: [],
    createdAt: new Date("2024-01-27"),
    createdBy: "admin",
  },
  {
    id: "28",
    name: "Sikat Gigi Formula Classic",
    description: "Sikat gigi manual bulu halus.",
    imageUrl: "https://via.placeholder.com/150",
    category: "Kesehatan",
    units: [],
    createdAt: new Date("2024-01-28"),
    createdBy: "admin",
  },
  {
    id: "29",
    name: "Dettol Hand Sanitizer 50ml",
    description: "Antiseptik tangan berbasis alkohol.",
    imageUrl: "https://via.placeholder.com/150",
    category: "Kesehatan",
    units: [],
    createdAt: new Date("2024-01-29"),
    createdBy: "admin",
  },
  {
    id: "30",
    name: "Coca Cola Kaleng 330ml",
    description: "Minuman bersoda dalam kemasan kaleng.",
    imageUrl: "https://via.placeholder.com/150",
    category: "Minuman",
    units: [],
    createdAt: new Date("2024-01-30"),
    createdBy: "admin",
  }
];